#!/usr/bin/env python3
"""Convert the Rocco Offroad logo PNG into an LVGL 1-bit image header.

The emblem is rendered into the full 128x32 frame, rotated 90 degrees so it
reads upright when the Corne sits on the desk (the OLEDs are mounted sideways).

Usage: gen_logo.py <input.png> <output.h>
"""
import sys
from PIL import Image

SCREEN_W, SCREEN_H = 128, 32
EMBLEM = 32  # emblem is circular; use the full screen height
THRESHOLD = 128  # 0-255; pixels darker than this light up on the OLED
ROTATE = 90  # degrees counter-clockwise; flip to 270 if the R reads upside down


def to_bitmap(path):
    im = Image.open(path).convert("LA")
    # Flatten alpha over white so transparent PNGs behave like the flat one
    gray = Image.new("L", im.size, 255)
    gray.paste(im.getchannel("L"), mask=im.getchannel("A"))
    gray = gray.resize((EMBLEM, EMBLEM), Image.LANCZOS)
    gray = gray.rotate(ROTATE, expand=True)

    canvas = Image.new("L", (SCREEN_W, SCREEN_H), 255)
    canvas.paste(gray, ((SCREEN_W - EMBLEM) // 2, (SCREEN_H - EMBLEM) // 2))
    return [[1 if canvas.getpixel((x, y)) < THRESHOLD else 0 for x in range(SCREEN_W)]
            for y in range(SCREEN_H)]


def emit(bitmap, name):
    data = bytearray()
    # LVGL indexed-1bit palette: index 0 = black (off), index 1 = white (lit)
    data += bytes([0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF])
    for row in bitmap:
        for byte_start in range(0, SCREEN_W, 8):
            byte = 0
            for bit in range(8):
                byte = (byte << 1) | row[byte_start + bit]
            data.append(byte)

    lines = [f"static const uint8_t {name}_map[] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    lines.append("};")
    lines.append(f"""
static const lv_img_dsc_t {name} = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {SCREEN_W},
    .header.h = {SCREEN_H},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};""")
    return "\n".join(lines)


def main():
    src, dst = sys.argv[1], sys.argv[2]
    header = "\n".join([
        "/* Generated by scripts/gen_logo.py — do not edit by hand. */",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        emit(to_bitmap(src), "rocco_logo"),
        "",
    ])
    with open(dst, "w") as f:
        f.write(header)
    print(f"wrote {dst}")


if __name__ == "__main__":
    main()
