#!/usr/bin/env python3
"""Generate a simplified Rocco Offroad emblem as an LVGL 1-bit image header.

Instead of downscaling the distressed logo (which turns to mush at 32px), this
redraws its structure natively: segmented ring, bold R, and the horizontal
speed bars — matching base-logo-final-rgb.svg but readable on a 0.91" OLED.

Rendered at high resolution, thresholded down to 32x32, then rotated 90 so it
reads upright with the keyboard on the desk.

Usage: gen_logo.py <output.h>
"""
import math
import sys
from PIL import Image, ImageDraw, ImageFont

SCREEN_W, SCREEN_H = 128, 32
EMBLEM = 32
SS = 8  # supersampling factor
ROTATE = 270  # degrees CCW; the OLED needs the emblem this way to read upright

FONTS = [
    "/System/Library/Fonts/Supplemental/Arial Black.ttf",
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
]


def load_font(size):
    for path in FONTS:
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    raise SystemExit("no suitable bold font found")


def draw_emblem():
    size = EMBLEM * SS
    im = Image.new("L", (size, size), 0)
    d = ImageDraw.Draw(im)
    c = size / 2

    # Segmented ring: 8 arcs with gaps, like the tread ring in the logo
    ring_w = int(2.5 * SS)
    r = c - ring_w / 2 - SS * 0.5
    box = [c - r, c - r, c + r, c + r]
    for i in range(8):
        start = i * 45 + 8
        d.arc(box, start, start + 29, fill=255, width=ring_w)

    # Speed bars: three short horizontal lines on each side at mid height
    bar_h = int(1.2 * SS)
    for dy in (-4, 0, 4):
        y0 = c + dy * SS - bar_h / 2
        d.rectangle([0, y0, 5 * SS, y0 + bar_h], fill=255)
        d.rectangle([size - 5 * SS, y0, size, y0 + bar_h], fill=255)

    # Bold centered R, slightly overflowing the ring like the original
    font = load_font(int(26 * SS))
    bbox = d.textbbox((0, 0), "R", font=font)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    d.text((c - w / 2 - bbox[0], c - h / 2 - bbox[1]), "R", fill=255, font=font,
           stroke_width=SS // 2, stroke_fill=255)

    return im


def to_bitmap():
    im = draw_emblem().resize((EMBLEM, EMBLEM), Image.LANCZOS)
    im = im.rotate(ROTATE, expand=True)
    canvas = Image.new("L", (SCREEN_W, SCREEN_H), 0)
    canvas.paste(im, ((SCREEN_W - EMBLEM) // 2, (SCREEN_H - EMBLEM) // 2))
    return [[1 if canvas.getpixel((x, y)) >= 128 else 0 for x in range(SCREEN_W)]
            for y in range(SCREEN_H)]


def emit(bitmap, name):
    data = bytearray([0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0xFF])
    for row in bitmap:
        for byte_start in range(0, SCREEN_W, 8):
            byte = 0
            for bit in range(8):
                byte = (byte << 1) | row[byte_start + bit]
            data.append(byte)
    lines = [f"static const uint8_t {name}_map[] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    lines.append("};")
    lines.append(f"""
static const lv_img_dsc_t {name} = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {SCREEN_W},
    .header.h = {SCREEN_H},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};""")
    return "\n".join(lines)


def main():
    dst = sys.argv[1]
    header = "\n".join([
        "/* Generated by scripts/gen_logo.py — do not edit by hand. */",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        emit(to_bitmap(), "rocco_logo"),
        "",
    ])
    with open(dst, "w") as f:
        f.write(header)
    print(f"wrote {dst}")


if __name__ == "__main__":
    main()
