#!/usr/bin/env python3
"""Generate bongo-cat frames as an LVGL 1-bit image header.

Solid-silhouette style: filled white cat with carved dark features, which reads
far better on a 1-bit OLED than outlines. Three 48x32 frames: idle (paws up),
left paw tapping, right paw tapping.

Usage: gen_bongo.py <output.h>
"""
import sys

W, H = 48, 32


def blank():
    return [[0] * W for _ in range(H)]


def px(g, x, y, v=1):
    if 0 <= x < W and 0 <= y < H:
        g[int(y)][int(x)] = v


def fill_ellipse(g, cx, cy, rx, ry, v=1):
    for y in range(int(cy - ry), int(cy + ry) + 1):
        for x in range(int(cx - rx), int(cx + rx) + 1):
            if ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2 <= 1.0:
                px(g, x, y, v)


def fill_circle(g, cx, cy, r, v=1):
    fill_ellipse(g, cx, cy, r, r, v)


def fill_triangle(g, p0, p1, p2, v=1):
    xs = [p[0] for p in (p0, p1, p2)]
    ys = [p[1] for p in (p0, p1, p2)]
    for y in range(max(0, min(ys)), min(H - 1, max(ys)) + 1):
        for x in range(max(0, min(xs)), min(W - 1, max(xs)) + 1):
            d1 = (x - p1[0]) * (p0[1] - p1[1]) - (p0[0] - p1[0]) * (y - p1[1])
            d2 = (x - p2[0]) * (p1[1] - p2[1]) - (p1[0] - p2[0]) * (y - p2[1])
            d3 = (x - p0[0]) * (p2[1] - p0[1]) - (p2[0] - p0[0]) * (y - p0[1])
            neg = d1 < 0 or d2 < 0 or d3 < 0
            pos = d1 > 0 or d2 > 0 or d3 > 0
            if not (neg and pos):
                px(g, x, y, v)


def hline(g, x0, x1, y, v=1):
    for x in range(x0, x1 + 1):
        px(g, x, y, v)


def cat(paw_left_down, paw_right_down):
    g = blank()

    # Ears (filled triangles), then the head (filled ellipse) on top
    fill_triangle(g, (17, 8), (21, 0), (27, 5))
    fill_triangle(g, (34, 5), (40, 0), (44, 8))
    fill_ellipse(g, 31, 15, 16, 12)

    # Face carved out in black: closed happy eyes and a small mouth
    hline(g, 23, 26, 13, 0)
    px(g, 23, 12, 0); px(g, 26, 12, 0)
    hline(g, 36, 39, 13, 0)
    px(g, 36, 12, 0); px(g, 39, 12, 0)
    hline(g, 29, 30, 18, 0)
    hline(g, 32, 33, 18, 0)
    px(g, 31, 17, 0)

    # Table: two-pixel edge along the bottom
    hline(g, 0, W - 1, 29)
    hline(g, 0, W - 1, 30)

    # Paws: filled circles with a dark outline ring so they stay readable when
    # they overlap the head or the table. Either raised or slamming down.
    def paw(cx, cy):
        fill_circle(g, cx, cy, 5, 0)
        fill_circle(g, cx, cy, 4)

    if paw_left_down:
        paw(7, 26)
        hline(g, 2, 4, 20, 1)  # motion tick
    else:
        paw(8, 19)
    if paw_right_down:
        paw(17, 26)
        hline(g, 12, 14, 20, 1)  # motion tick
    else:
        paw(18, 23)

    return g


def emit(bitmap, name):
    data = bytearray([0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0xFF])
    for row in bitmap:
        for byte_start in range(0, W, 8):
            byte = 0
            for bit in range(8):
                byte = (byte << 1) | row[byte_start + bit]
            data.append(byte)
    lines = [f"static const uint8_t {name}_map[] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    lines.append("};")
    lines.append(f"""
static const lv_img_dsc_t {name} = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {W},
    .header.h = {H},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};""")
    return "\n".join(lines)


def main():
    dst = sys.argv[1]
    parts = [
        "/* Generated by scripts/gen_bongo.py — do not edit by hand. */",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        emit(cat(False, False), "bongo_idle"),
        emit(cat(True, False), "bongo_tap_left"),
        emit(cat(False, True), "bongo_tap_right"),
        "",
    ]
    with open(dst, "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {dst}")


if __name__ == "__main__":
    main()
