#!/usr/bin/env python3
"""Generate simplified bongo-cat frames as an LVGL 1-bit image header.

Three 48x32 frames: idle (paws up), left paw tapping, right paw tapping.
The art is drawn procedurally so it can be tweaked via the constants below.

Usage: gen_bongo.py <output.h>
"""
import math
import sys

W, H = 48, 32


def blank():
    return [[0] * W for _ in range(H)]


def set_px(g, x, y):
    if 0 <= x < W and 0 <= y < H:
        g[int(y)][int(x)] = 1


def line(g, x0, y0, x1, y1):
    steps = max(abs(x1 - x0), abs(y1 - y0), 1)
    for i in range(int(steps) + 1):
        t = i / steps
        set_px(g, round(x0 + (x1 - x0) * t), round(y0 + (y1 - y0) * t))


def ellipse(g, cx, cy, rx, ry, a0=0.0, a1=2 * math.pi):
    steps = int(20 * max(rx, ry))
    for i in range(steps + 1):
        a = a0 + (a1 - a0) * i / steps
        set_px(g, round(cx + rx * math.cos(a)), round(cy + ry * math.sin(a)))


def blob(g, cx, cy, r):
    for y in range(int(cy - r), int(cy + r) + 1):
        for x in range(int(cx - r), int(cx + r) + 1):
            if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
                set_px(g, x, y)


def cat(paw_left_down, paw_right_down):
    g = blank()
    # Head: wide ellipse, right of center
    ellipse(g, 30, 13, 16, 10)
    # Ears: two triangles poking above the head
    line(g, 18, 6, 21, 0); line(g, 21, 0, 26, 4)
    line(g, 35, 3, 40, 0); line(g, 40, 0, 43, 5)
    # Eyes and mouth
    blob(g, 25, 12, 1); blob(g, 36, 12, 1)
    set_px(g, 29, 16); set_px(g, 30, 17); set_px(g, 31, 16); set_px(g, 32, 17); set_px(g, 33, 16)
    # Table edge, bottom-left
    line(g, 0, 22, 20, 32)
    # Paws: blobs either raised near the head or planted on the table
    if paw_left_down:
        blob(g, 5, 26, 3)
    else:
        blob(g, 9, 17, 3)
    if paw_right_down:
        blob(g, 15, 30, 3)
    else:
        blob(g, 18, 21, 3)
    return g


def emit(bitmap, name):
    data = bytearray([0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF])
    for row in bitmap:
        for byte_start in range(0, W, 8):
            byte = 0
            for bit in range(8):
                byte = (byte << 1) | row[byte_start + bit]
            data.append(byte)
    lines = [f"static const uint8_t {name}_map[] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    lines.append("};")
    lines.append(f"""
static const lv_img_dsc_t {name} = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {W},
    .header.h = {H},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};""")
    return "\n".join(lines)


def main():
    dst = sys.argv[1]
    parts = [
        "/* Generated by scripts/gen_bongo.py — do not edit by hand. */",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        emit(cat(False, False), "bongo_idle"),
        emit(cat(True, False), "bongo_tap_left"),
        emit(cat(False, True), "bongo_tap_right"),
        "",
    ]
    with open(dst, "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {dst}")


if __name__ == "__main__":
    main()
